export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const FETCH_SINGLE_RECORD = "FETCH_SINGLE_RECORD";
export const FETCH_SINGLE_ERROR = "FETCH_SINGLE_ERROR";